grep -w "&H2EDD2F" out.csv
grep -w "&H2EDD33" out.csv
grep -w "&H2EDD37" out.csv
grep -w "&H2EDD3B" out.csv
grep -w "&H2EDD4B" out.csv
grep -w "&H2EDD4F" out.csv
grep -w "&H2EDD53" out.csv
grep -w "&H2EDD57" out.csv
grep -w "&H2EDD67" out.csv
grep -w "&H2EDD6B" out.csv
grep -w "&H2EDD6F" out.csv
grep -w "&H2EDD73" out.csv
grep -w "&H2EDD83" out.csv
grep -w "&H2EDD87" out.csv
grep -w "&H2EDD8B" out.csv
grep -w "&H2EDD8F" out.csv
grep -w "&H2EDD9F" out.csv
grep -w "&H2EDDA3" out.csv
grep -w "&H2EDDA7" out.csv
grep -w "&H2EDDAB" out.csv
grep -w "&H2EDDBB" out.csv
grep -w "&H2EDDBF" out.csv
grep -w "&H2EDDC3" out.csv
grep -w "&H2EDDC7" out.csv
grep -w "&H2EDDD7" out.csv
grep -w "&H2EDDDB" out.csv
grep -w "&H2EDDDF" out.csv
grep -w "&H2EDDE3" out.csv
grep -w "&H2EDDF3" out.csv
grep -w "&H2EDDF7" out.csv
grep -w "&H2EDDFB" out.csv
grep -w "&H2EDDFF" out.csv
grep -w "&H2EDE0F" out.csv
grep -w "&H2EDE13" out.csv
grep -w "&H2EDE17" out.csv
grep -w "&H2EDE1B" out.csv
grep -w "&H2EDE2B" out.csv
grep -w "&H2EDE2F" out.csv
grep -w "&H2EDE33" out.csv
grep -w "&H2EDE37" out.csv
grep -w "&H2EDE47" out.csv
grep -w "&H2EDE4B" out.csv
grep -w "&H2EDE4F" out.csv
grep -w "&H2EDE53" out.csv
grep -w "&H2EDE63" out.csv
grep -w "&H2EDE67" out.csv
grep -w "&H2EDE6B" out.csv
grep -w "&H2EDE6F" out.csv
grep -w "&H2EDE7F" out.csv
grep -w "&H2EDE83" out.csv
grep -w "&H2EDE87" out.csv
grep -w "&H2EDE8B" out.csv
grep -w "&H2EDE9B" out.csv
grep -w "&H2EDE9F" out.csv
grep -w "&H2EDEA3" out.csv
grep -w "&H2EDEA7" out.csv
grep -w "&H2EDEB7" out.csv
grep -w "&H2EDEBB" out.csv
grep -w "&H2EDEBF" out.csv
grep -w "&H2EDEC3" out.csv
grep -w "&H2EDED3" out.csv
grep -w "&H2EDED7" out.csv
grep -w "&H2EDEDB" out.csv
grep -w "&H2EDEDF" out.csv
grep -w "&H2EDEEF" out.csv
grep -w "&H2EDEF3" out.csv
grep -w "&H2EDEF7" out.csv
grep -w "&H2EDEFB" out.csv
grep -w "&H2EDF0B" out.csv
grep -w "&H2EDF0F" out.csv
grep -w "&H2EDF13" out.csv
grep -w "&H2EDF17" out.csv
grep -w "&H2EDF27" out.csv
grep -w "&H2EDF2B" out.csv
grep -w "&H2EDF2F" out.csv
grep -w "&H2EDF33" out.csv
grep -w "&H2EDF43" out.csv
grep -w "&H2EDF47" out.csv
grep -w "&H2EDF4B" out.csv
grep -w "&H2EDF4F" out.csv
grep -w "&H2EDF5F" out.csv
grep -w "&H2EDF63" out.csv
grep -w "&H2EDF67" out.csv
grep -w "&H2EDF6B" out.csv
grep -w "&H2EDF7B" out.csv
grep -w "&H2EDF7F" out.csv
grep -w "&H2EDF83" out.csv
grep -w "&H2EDF87" out.csv
grep -w "&H2EDF97" out.csv
grep -w "&H2EDF9B" out.csv
grep -w "&H2EDF9F" out.csv
grep -w "&H2EDFA3" out.csv
grep -w "&H2EDFB3" out.csv
grep -w "&H2EDFB7" out.csv
grep -w "&H2EDFBB" out.csv
grep -w "&H2EDFBF" out.csv
grep -w "&H2EDFCF" out.csv
grep -w "&H2EDFD3" out.csv
grep -w "&H2EDFD7" out.csv
grep -w "&H2EDFDB" out.csv
grep -w "&H2EDFEB" out.csv
grep -w "&H2EDFEF" out.csv
grep -w "&H2EDFF3" out.csv
grep -w "&H2EDFF7" out.csv
grep -w "&H2EE007" out.csv
grep -w "&H2EE00B" out.csv
grep -w "&H2EE00F" out.csv
grep -w "&H2EE013" out.csv
grep -w "&H2EE023" out.csv
grep -w "&H2EE027" out.csv
grep -w "&H2EE02B" out.csv
grep -w "&H2EE02F" out.csv
grep -w "&H2EE03F" out.csv
grep -w "&H2EE043" out.csv
grep -w "&H2EE047" out.csv
grep -w "&H2EE04B" out.csv
grep -w "&H2EE05B" out.csv
grep -w "&H2EE05F" out.csv
grep -w "&H2EE063" out.csv
grep -w "&H2EE067" out.csv
grep -w "&H2EE077" out.csv
grep -w "&H2EE07B" out.csv
grep -w "&H2EE07F" out.csv
grep -w "&H2EE083" out.csv
grep -w "&H2EE093" out.csv
grep -w "&H2EE097" out.csv
grep -w "&H2EE09B" out.csv
grep -w "&H2EE09F" out.csv
grep -w "&H2EE0AF" out.csv
grep -w "&H2EE0B3" out.csv
grep -w "&H2EE0B7" out.csv
grep -w "&H2EE0BB" out.csv
grep -w "&H2EE0CB" out.csv
grep -w "&H2EE0CF" out.csv
grep -w "&H2EE0D3" out.csv
grep -w "&H2EE0D7" out.csv
grep -w "&H2EE0E7" out.csv
grep -w "&H2EE0EB" out.csv
grep -w "&H2EE0EF" out.csv
grep -w "&H2EE0F3" out.csv
grep -w "&H2EE103" out.csv
grep -w "&H2EE107" out.csv
grep -w "&H2EE10B" out.csv
grep -w "&H2EE10F" out.csv
grep -w "&H2EE11F" out.csv
grep -w "&H2EE123" out.csv
grep -w "&H2EE127" out.csv
grep -w "&H2EE12B" out.csv
grep -w "&H2EE13B" out.csv
grep -w "&H2EE13F" out.csv
grep -w "&H2EE143" out.csv
grep -w "&H2EE147" out.csv
grep -w "&H2EE157" out.csv
grep -w "&H2EE15B" out.csv
grep -w "&H2EE15F" out.csv
grep -w "&H2EE163" out.csv
grep -w "&H2EE173" out.csv
grep -w "&H2EE177" out.csv
grep -w "&H2EE17B" out.csv
grep -w "&H2EE17F" out.csv
grep -w "&H2EE18F" out.csv
grep -w "&H2EE193" out.csv
grep -w "&H2EE197" out.csv
grep -w "&H2EE19B" out.csv
grep -w "&H2EE1AB" out.csv
grep -w "&H2EE1AF" out.csv
grep -w "&H2EE1B3" out.csv
grep -w "&H2EE1B7" out.csv
grep -w "&H2EE1C7" out.csv
grep -w "&H2EE1CB" out.csv
grep -w "&H2EE1CF" out.csv
grep -w "&H2EE1D3" out.csv
grep -w "&H2EE1E3" out.csv
grep -w "&H2EE1E7" out.csv
grep -w "&H2EE1EB" out.csv
grep -w "&H2EE1EF" out.csv
grep -w "&H2EE1FF" out.csv
grep -w "&H2EE203" out.csv
grep -w "&H2EE207" out.csv
grep -w "&H2EE20B" out.csv
grep -w "&H2EE21B" out.csv
grep -w "&H2EE21F" out.csv
grep -w "&H2EE223" out.csv
grep -w "&H2EE227" out.csv
grep -w "&H2EE237" out.csv
grep -w "&H2EE23B" out.csv
grep -w "&H2EE23F" out.csv
grep -w "&H2EE243" out.csv
grep -w "&H2EE253" out.csv
grep -w "&H2EE257" out.csv
grep -w "&H2EE25B" out.csv
grep -w "&H2EE25F" out.csv
